---
- name: Setup DB Server
  hosts: dbsrvgrp
  become: yes
  tasks:
   - name:  Installing MySQl Python
     yum:
      name: MySQL-python
      state: present
   
   - name: Installing MariaB
     yum:     
      name: mariadb-server
      state: present
   - name: Starting DB Service
     service:
      name: mariadb
      state: started
      enabled: yes
   - name: Create a new database with name 'accounts'
     mysql_db:
      name: accounts
      state: present  


   - name: Create database user with name 'admin' and password '12345' with all database privileges
     mysql_user:
      name: admin
      password: 12345
      priv: '*.*:ALL'
      state: present   



