---
- name: Setup DB Server
  hosts: dbsrvgrp
  become: yes
  vars:
    dbname: msdb
    dbuser: myuser
    dbpass: admin1234  
         
  tasks:
   - name:  Installing MySQl Python
     yum:
      name: MySQL-python
      state: present
   
   - name: Installing MariaB
     yum:     
      name: mariadb-server
      state: present
   - name: Starting DB Service
     service:
      name: mariadb
      state: started
      enabled: yes
   - name: Create a new database 
     mysql_db:
      name: "{{dbname}}"
      state: present  


   - name: Create database user with name 'admin' and password '12345' with all database privileges
     mysql_user:
      name: "{{dbuser}}"
      password: "{{dbpass}}"
      priv: '*.*:ALL'
      state: present   



